import userImg from './img/userTest.jpg';
export const users = [
    {
        name:'Sohee',
        username:'dogSohee',
        image:userImg
    },
    {
        name:'Lorente',
        username:'misslorennn',
        image:userImg
    },
    {
        name:'Ronaldo',
        username:'cristianoronaldo',
        image:userImg
    },
    {
        name:'Leonel',
        username:'leomessi',
        image:userImg
    },
    {
        name:'Sohee',
        username:'dogSohee',
        image:userImg
    },
    {
        name:'Lorente',
        username:'misslorennn',
        image:userImg
    },
    {
        name:'Ronaldo',
        username:'cristianoronaldo',
        image:userImg
    },
    {
        name:'Leonel',
        username:'leomessi',
        image:userImg
    },
    {
        name:'Sohee',
        username:'dogSohee',
        image:userImg
    },
    {
        name:'Lorente',
        username:'misslorennn',
        image:userImg
    },
    {
        name:'Ronaldo',
        username:'cristianoronaldo',
        image:userImg
    },
    {
        name:'eaf',
        username:'leomefafessi',
        image:userImg
    }
]